version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  bobby:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
      - run: echo "A first hello"
  sally:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
      - run: echo "Second hello"
  workflows:
    version: 2.1
    bobby_sally:
      jobs:
        - bobby
        - sally